### ISSUE TITLE
How can i remove the selected background & animation?

### ISSUE THREAD

**Issue by num-js** [vamsiabishek/react-native-number-slider#3]
I just want a simple slider with numbers & i don't want the background color & selectedBackground color, how can i remove that?

**Comment by vamsiabishek** [comment]
You can pass the properties as  `transparent` instead of a color

**Comment by vamsiabishek** [comment]
> I just want a simple slider with numbers & i don't want the background color & selectedBackground color, how can i remove that?

You can pass the properties as transparent instead of a color
